#!/bin/bash
#
# Prints one or more random /24 subnets within the 10.33.0.0/16 Test VPC
# that are not already used by any cluster under clusters/. The number
# of subnets desired may be specified as an optional integer argument.
#
# Example:
#
# $ misc/find-unused-subnets 3
# 10.33.28.0/24
# 10.33.34.0/24
# 10.33.251.0/24
#
# If you want something smaller, split up a /24 subnet yourself.

IFS=
set -e -u

misc=$(dirname $0)
clusters=$(realpath $misc/../clusters)

# We don't use git ls-files here, because there may be uncommitted
# clusters.

find $clusters -name config.yml | \
    xargs grep -hEo '10\.33\.[0-9]{1,3}\.[0-9]{1,3}' | \
        sed -e 's/^10.33.//' -e 's/\..*$//' | \
            sort -un > /tmp/subnets

seq 0 254 | grep -vxf /tmp/subnets | shuf | head -n "${1:-1}" | \
    sed -e 's/^/10.33./' -e 's,$,.0/24,'
