#!/usr/bin/env perl
#
# This script is meant to be used as follows:
#
#   cluster_tags=$($libdir/cluster-tags foo=bar …)
#   cat <<CONFIG
#   cluster_tags: $cluster_tags
#   …
#   CONFIG
#
# The single-line output in YAML hash format contains zero or more tag
# definitions, as set by key=value pairs specified on the command line
# and options passed to tpaexec configure (e.g., ``--owner Owner``).

my @output;

my %envvars = (
    CLUSTER_TAGS_OWNER => "Owner"
);
foreach my $k (keys %envvars) {
    if ($ENV{$k}) {
        push @output, "$envvars{$k}: $ENV{$k}";
    }
}
foreach my $s (@ARGV) {
    my ($k, $v) = split /=/, $s, 2;
    push @output, "$k: $v";
}

print "{@{[join(', ', @output)]}}\n";
