#!/usr/bin/env perl
#
# This script is meant to be used as follows:
#
#   cluster_vars=$($libdir/cluster-vars key=value …)
#   cat <<CONFIG
#   cluster_vars: $cluster_vars
#   …
#   CONFIG
#
# The single-line output in YAML hash format contains zero or more vars,
# as set by key=value pairs specified on the command line and options
# passed to tpaexec configure (e.g., ``--postgres-package-version``).
# Not everything that belongs in cluster_vars is configurable here.

my @output;

my %envvars = (
    POSTGRES_VERSION => "postgres_version"
    , POSTGRES_PACKAGE_VERSION => "postgres_package_version"
    , REPMGR_PACKAGE_VERSION => "repmgr_package_version"
    , BARMAN_PACKAGE_VERSION => "barman_package_version"
    , TPA_2Q_REPO => "tpa_2q_repo"
);
foreach my $k (keys %envvars) {
    if ($ENV{$k}) {
        push @output, "$envvars{$k}: $ENV{$k}";
    }
}
foreach my $s (@ARGV) {
    my ($k, $v) = split /=/, $s, 2;
    push @output, "$k: $v";
}

print "{@{[join(', ', @output)]}}\n";
