#!/usr/bin/env perl
#
# This script is meant to be used as follows:
#
# cat <<CONFIG
# cluster_tags: $($libdir/cluster-tags)
# …
# CONFIG
#
# The output contains zero or more tag definitions, as set by options
# passed to tpaexec configure (e.g., ``--owner Owner``).

my @output;

if ($ENV{CLUSTER_TAGS_OWNER}) {
    push @output, "  Owner: $ENV{CLUSTER_TAGS_OWNER}";
}

if (@output) {
    print join("\n", "", @output), "\n";
}
else {
    print "{}\n";
}
