#!/bin/bash
# Copyright © 2ndQuadrant Limited <info@2ndquadrant.com>
#
# hostnames 33
#   Returns 33 randomly-selected hostnames
#
# hostnames 33 /usr/share/dict/words
#   Returns 33 randomly-selected hostnames from /usr/share/dict/words
#
# hostnames 33 /usr/share/dict/words '^[a-m]{3}[n-z]{3,4}$'
#   Returns 33 randomly-selected hostnames from /usr/share/dict/words
#   that match the given pattern

IFS=$' \t\n'
set -eu

libdir=$(dirname "$0")
wanted=${1:?Number of hostnames not specified}
namesfile=${2:-${HOSTNAMES_FROM:=$libdir/hostnames.txt}}
pattern=${3:-${HOSTNAMES_PATTERN:='[a-zA-Z0-9-]*'}}
order=${HOSTNAMES_SORTED_BY:---random-sort}

type realpath &>/dev/null && namesfile=$(realpath "$namesfile")
if [[ ! -f $namesfile ]]; then
    echo "ERROR: could not open hostname list: $namesfile" >&2
    exit 1
fi

if [[ ${HOSTNAMES_UNSORTED:-'False'} == 'True' ]]; then
    mapfile -t names < <(grep -xE "$pattern" "$namesfile"|head -"$wanted")
else
    mapfile -t names < <(grep -xE "$pattern" "$namesfile"|sort "$order"|head -"$wanted")
fi
if [[ "${#names[@]}" -lt $wanted ]];
then
    echo "ERROR: found only ${#names[@]}/$wanted names matching '$pattern' in $namesfile" >&2
    exit 1
fi

echo "${names[@]}"
