#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

from tpaexec.password import generate_password


def main():
    """
    password.pyPrint a random password to stdout.

    Generated using the tpaexec library function (which see).
    Does not take any options.
    """
    print(generate_password())


if __name__ == "__main__":
    main()
