#!/bin/bash
# Copyright © EnterpriseDB Corporation
#
# Generates a random password to stdout.
#
# We would prefer to use pwgen, but it is not always available (even on
# Linux), so we fall back to using shasum (should be available on Mac OS
# X too). Other methods can be added here if necessary to support other
# platforms.

if command -v pwgen &>/dev/null; then
    p=$(pwgen -1y 32 -r '\\":'"'")
elif command -v shasum &>/dev/null; then
    p=$(head -c128 /dev/urandom|shasum|head -c32)
else
    exit 1
fi

echo "$p"
