---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- include_role:
    name: watchdog
  when: >
    'postgres' in role
    and patroni_watchdog_enabled|default(false)
    and task_selector|permits('watchdog')

- block:
    - include_role:
        name: patroni/pkg
        tasks_from: dependencies.yml
    - include_role:
        name: "patroni/{{ patroni_installation_method }}"
  when: >
    'postgres' in role
    and task_selector|permits(patroni_installation_method)

- include_role: name=postgres/pgpass
  vars:
    pgpass_users:
      - "{{ replication_user }}"
  when: 
    role|intersect(['primary','replica'])

# This password will be used when creating the etcd user for Patroni. As that can only
# occur once the etcd cluster is up and running, and we might need the password before
# that stage (for example when setting up the patroni/config or patorni/final roles),
# we create the password here.
- name: "Generate password for the Patroni etcd user {{ patroni_etcd_user }}"
  when: >
    etcd_authentication_mode == 'basic'
  include_role:
    name: secret
  vars:
    secret_name: "{{ patroni_etcd_user }}_password"
    generate_password: true

# Copy etcd facts which are needed for Patroni configuration and setup.
# These facts are not static configuration options which are known from the beginning,
# but dynamic facts generated by the etcd nodes based on the state at runtime.
- name: "Copy required etcd facts from an etcd host"
  set_fact:
    etcd_protocol: "{{ hostvars[_source_etcd_host].etcd_protocol }}"
  vars:
    _source_etcd_host: "{{ groups['role_etcd'][0] }}"

- include_role:
    name: patroni/config
  when: >
    'postgres' in role
    and task_selector|permits('config')

- include_role:
    name: patroni/service
  when: >
    'postgres' in role
    and task_selector|permits('service')
