---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- include_role:
    name: pem/agent/pkg
  vars:
    _allowerasing: "{{ ansible_os_family == 'RedHat' }}"
  when: >
    task_selector|selects('pem-agent', 'pkg')
