sonar.python.coverage.reportPaths=coverage-reports/coverage.xml
sonar.python.xunit.reportPath=coverage-reports/results.xml
sonar.coverage.exclusions=**/lib/tests/**/*.*, **/docs/**/*.*, test-output/**/*.*, coverage-reports/*.*
sonar.exclusions=**/docs/**/*.*, test-output/**/*.*, **/.tox/**/*.*
sonar.test.exclusions=**/lib/tests/**/*.*
