---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- name: Run post-upgrade health check for the cluster
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: all
  tasks: 
  - name: Run Barman checks
    when: "'barman' in role"
    block:
    - name: Start WAL receiver on barman nodes (it is stopped if Barman was not upgraded)
      include_role:
        name: barman
        tasks_from: server-start-receive-wal.yml

    - name: Check barman health
      include_role: 
        name: test
        tasks_from: barman/basic.yml
  
  - name: Run pg-backup-api checks
    include_role:
      name: test
      tasks_from: pg-backup-api.yml
    when: 
    - "'barman' in role"
    - enable_pg_backup_api|default(False)|bool

  - name: Run PgBouncer checks
    include_role: 
      name: test
      tasks_from: pgbouncer/basic.yml
    when: "'pgbouncer' in role"
