---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- name: Run precondition checks for before upgrade
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: all
  tasks: 
  - name: Ensure upgrade is not invoked for a shared PEM server
    fail: 
      fail_msg: "Upgrading with TPA is not supported for shared PEM servers"
    when: (pem_shared|default(false)) is true

  - name: Ensure upgrade is not invoked for a shared Barman server
    fail: 
      fail_msg: "Upgrading with TPA is not supported for shared Barman servers"
    when: (barman_shared|default(false)) is true
