# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 08:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import tpa.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tpa', '000_ext_hstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('user_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('cluster_type', models.CharField(choices=[('P', 'PostgreSQL'), ('B', 'Bidirectional replication'), ('X', 'Postgres XL')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('user_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('hostname', tpa.models.TextLineField(max_length=255)),
                ('domain', tpa.models.TextLineField(max_length=255)),
                ('assign_eip', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('hardware_configuration', tpa.models.TextLineField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('user_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('shared_identity', tpa.models.TextLineField(max_length=255)),
                ('shared_secret', tpa.models.TextLineField(max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('location', tpa.models.TextLineField(max_length=255, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('user_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Instance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleLink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('user_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('client_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='tpa.Role')),
                ('server_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_links', to='tpa.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('user_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('netmask', tpa.models.TextLineField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Cluster')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.ProviderCredential')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('user_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('volume_type', tpa.models.TextLineField(max_length=255)),
                ('volume_size', models.PositiveIntegerField()),
                ('delete_on_termination', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Instance')),
                ('tentant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolumeUse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('user_tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Role')),
                ('tentant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Volume')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', tpa.models.TextLineField(db_index=True, max_length=255)),
                ('location', tpa.models.TextLineField(max_length=255, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subnet',
            name='tentant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Zone'),
        ),
        migrations.AddField(
            model_name='rolelink',
            name='tentant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AddField(
            model_name='role',
            name='tentant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='tentant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AddField(
            model_name='instancetype',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Zone'),
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.InstanceType'),
        ),
        migrations.AddField(
            model_name='instance',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Subnet'),
        ),
        migrations.AddField(
            model_name='instance',
            name='tentant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='tentant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='volumeuse',
            unique_together=set([('role', 'volume')]),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set([('instance', 'name')]),
        ),
    ]
