# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:23
from __future__ import unicode_literals

from django.db import migrations
import tpa.models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0001_auto_20161123_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instancetype',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rolelink',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volumetype',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volumeuse',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=tpa.models.TextLineField(blank=True, db_index=True, max_length=255),
        ),
    ]
