# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import tpa.models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1000_data_provider_aws'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpc',
            name='cluster',
            field=tpa.models.OwnerKey(default='8d4ad6a9-e679-4662-acac-ce25e1f4246d', on_delete=django.db.models.deletion.CASCADE, to='tpa.Cluster'),
            preserve_default=False,
        ),
    ]
