# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1000_data_provider_aws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tpa.InstanceType'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tpa.Subnet'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='instancetype',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_types', to='tpa.Zone'),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='tpa.Provider'),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='region',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='tpa.Provider'),
        ),
        migrations.AlterField(
            model_name='role',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tpa.Instance'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='rolelink',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='tpa.Cluster'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='tpa.ProviderCredential'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='vpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='tpa.VPC'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='tpa.Zone'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='tpa.Instance'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='volumetype',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_types', to='tpa.Provider'),
        ),
        migrations.AlterField(
            model_name='volumeuse',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_volumes', to='tpa.Role'),
        ),
        migrations.AlterField(
            model_name='volumeuse',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='volumeuse',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by_roles', to='tpa.Volume'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpcs', to='tpa.Provider'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tpa.Tenant'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='tpa.Region'),
        ),
    ]
