# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1001_vpc_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='instance',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='rolelink',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='volume',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='volumeuse',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='user_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
