# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 06:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import tpa.models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1001_auto_20161128_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='subnet',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tpa.Subnet'),
        ),
        migrations.AlterField(
            model_name='instancetype',
            name='zone',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_types', to='tpa.Zone'),
        ),
        migrations.AlterField(
            model_name='region',
            name='provider',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='tpa.Provider'),
        ),
        migrations.AlterField(
            model_name='role',
            name='instance',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tpa.Instance'),
        ),
        migrations.AlterField(
            model_name='rolelink',
            name='client_role',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='tpa.Role'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='cluster',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='tpa.Cluster'),
        ),
        migrations.AlterField(
            model_name='volumetype',
            name='provider',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_types', to='tpa.Provider'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='region',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='tpa.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='rolelink',
            unique_together=set([('client_role', 'server_role')]),
        ),
    ]
