# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 15:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1002_auto_20161202_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ssh_public_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
