# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1006_role_process_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='process_type',
            new_name='role_type',
        ),
    ]
