# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 20:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import tpa.models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1007_auto_20170131_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancetype',
            name='hardware_configuration',
        ),
        migrations.AddField(
            model_name='instancetype',
            name='hardware',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=tpa.models.TextLineField(choices=[('adhoc', 'adhoc'), ('barman', 'barman'), ('bdr', 'bdr'), ('control', 'control'), ('coordinator', 'coordinator'), ('datanode', 'datanode'), ('datanode-replica', 'datanode-replica'), ('gtm', 'gtm'), ('log-server', 'log-server'), ('monitor', 'monitor'), ('openvpn-server', 'openvpn-server'), ('pgbouncer', 'pgbouncer'), ('primary', 'primary'), ('replica', 'replica'), ('witness', 'witness')], default='adhoc', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
