# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1008_auto_20170217_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancetype',
            name='memory',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instancetype',
            name='vcpus',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
