# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tpa.models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1009_auto_20170220_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_id', models.TextField(unique=True)),
                ('new_tenant_name', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='volume',
            name='instance',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='tpa.Instance'),
        ),
        migrations.AlterField(
            model_name='volumeuse',
            name='role',
            field=tpa.models.OwnerKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_volumes', to='tpa.Role'),
        ),
    ]
