# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1010_auto_20170323_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvitation',
            name='id',
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
