# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '1011_auto_20170323_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='parent_cluster',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tpa.Cluster'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='provision_state',
            field=models.CharField(choices=[('D', 'Design'), ('R', 'Requested'), ('P', 'Provisioned'), ('H', 'Historical'), ('T', 'Template')], default='D', max_length=1),
        ),
    ]
