#!/bin/bash
#
# Synopsis:
#
# clusters/images/build-images [-r] [PGDG|2ndQPostgres|…] [9.5|9.6|…]

IFS=
set -e -u

if [ ! -d clusters/images ]; then
    echo "Please run clusters/images/build-images (from the TPA/CustomCloud directory)"
    exit
fi

opt=${1:-""}
if [ "$opt" = "-r" ]; then
    shift
    utils/ansible-playbook clusters/images/generate-config.yml
fi

variant=${1:-"PGDG"}
version=${2:-"9.6"}
suffix=${3:-""}

utils/provision images -v

# Wait for a while for the instances to replace their SSH host keys.
sleep 120

utils/deploy images/deploy-$variant.yml -v \
    -e postgres_variant=$variant -e postgres_version=$version -e suffix=$suffix
utils/ansible-cluster images/generate-amis.yml -v \
    -e postgres_variant=$variant -e postgres_version=$version -e suffix=$suffix

utils/deprovision images -v
rm -rf clusters/images/id_tpaimages* \
    clusters/images/inventory/ec2.* \
    clusters/images/{hostkeys,vault}
