---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

# This playbook performs BDR 4→5 major version upgrades for PGD-Always-ON
# clusters. It requires that the cluster has been reconfigured from
# BDR-Always-ON to PGD-Always-ON using `tpaexec reconfigure` beforehand.
#
# The process is:
# 1. Check that the cluster looks normal before doing anything.
# 2. Then, for each Postgres instance:
#    a. Fence the node (via harp)
#    b. Stop, update, and restart Postgres
#    c. Unfence the node
#    d. Wait for the cluster to settle before moving on
# 3. Perform v5-specific tasks:
#    a. Upgrade pgd-cli
#    b. Repeat v5-specific BDR configuration, including:
#       i. Set node_kind for each instance
#       ii. Create node groups and set group options
#       iii. Create and configure proxies
#    c. Replace harp-proxy with pgd-proxy
#    d. Completely remove harp
# 4. Check that the cluster looks normal at the end

- name: Run BDR/PGD-specific health checks before upgrade
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_bdr
  tasks:
  # We require at least BDR 4.3 to start with, because older BDR versions
  # don't have an extension upgrade path to 5.2.
  - name: Ensure that BDR major version upgrades start from a recent version of BDR v4
    assert:
      that: all_bdr_versions|select('version', '4.3', '<')|list is empty
      fail_msg: >-
        Please upgrade to the latest available BDR 4.x release before trying to
        upgrade to PGD 5.2
    when:
      inventory_hostname == first_bdr_primary

  - name: Log pgd-cli diagnostic output
    include_role:
      name: test
      tasks_from: pgd-cli/info.yml
    vars:
      bdr_version: "{{ bdrdb_major_version }}"
    when:
      inventory_hostname == first_bdr_primary

# As a precaution, we refuse to start any upgrade if harp-proxy is
# unhealthy. In a 4→5 upgrade, harp-proxy is still the active proxy.

- name: Check proxy status before upgrade
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_harp-proxy:role_pgd-proxy:role_pgbouncer
  tasks:

  - name: Record harp-proxy endpoint DSN for monitoring
    set_fact:
      harp_proxy_endpoint:
        "{{ bdr_node_route_dsn|dbname(bdr_database, user=postgres_user, port=harp_proxy_port) }}"
    when: >
      'harp-proxy' in role

  - name: Check harp-proxy status
    include_role:
      name: test
      tasks_from: harp-proxy/basic.yml
    when: >
      'harp-proxy' in role

# Ascertain the status/health of PgBouncer, pg-backup-api and Barman BEFORE upgrade
# If any fail, the upgrade playbook will bail out.
# NOTE: The Barman WAL-receiver is stopped after this play is run,
# as we do not want new backup jobs to start mid-upgrade.
- name: Import pre-upgrade common-component health-checks
  import_playbook: "{{ tpa_dir }}/architectures/common/playbooks/pre_upgrade_checks.yml"

- name: Check if pgd-cli version can be upgraded
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_bdr:role_pgdcli:&g_update_hosts
  tasks:
  - when:
    - upgrade_selector|strict_selects('pgdcli') or upgrade_selector|strict_selects('all')
    - (('bdr' in role  or 'pgd-proxy' in role) and bdrdb_major_version is version('5', '<=')) or 'pgdcli' in role
    block:
    - name: Define pgdcli package version if not defined in config.yml
      set_fact:
        pgdcli_package_version: "{{ bdr_package_version }}"
      when:
      - pgdcli_package_version is not defined
      - bdr_package_version is defined

    - name: Check if pgd-cli can be updated to specified package version
      include_role:
        name: pgdcli/pkg
        tasks_from: check-update.yml
      when: pgdcli_package_version is defined

    - set_fact:
        can_upgrade_pgdcli: "{{ pgdcli_package_update | default(true) }}"

# We start a program that stays connected to the active harp-proxy
# instances and repeatedly runs queries, reporting on any interruptions
# (some brief interruptions are expected during fencing).
- name: Start monitoring proxy downtime
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_bdr
  tasks:
  - include_role:
      name: test
      tasks_from: proxy-monitor/start.yml
    vars:
      conninfos:
        "{{ groups['role_harp-proxy']|default([])
            |map('extract', hostvars, 'harp_proxy_endpoint')
            |list }}"
    when:
      inventory_hostname == first_bdr_primary
      and enable_proxy_monitoring

# Now that we're convinced the cluster is in a reasonable initial state,
# we start the update process one by one on the instances.
- name: Update postgres on instances in cluster {{ cluster_dir }}
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_postgres:&g_update_hosts:!role_pem-server
  serial: 1
  tasks:
  - name: Fence the node before upgrade
    include_role:
      name: postgres/bdr
      tasks_from: fence.yml
    vars:
      failover_manager: harp
    when:
      - "'bdr' in role"
      - inventory_hostname in first_bdr_primary_candidates

  - include_role:
      name: pgd_proxy/dbuser
      apply:
        tags: [pgd-proxy, dbuser]
    when:
      failover_manager == 'pgd'
      and 'bdr' in role
      and 'pem-server' not in role

  - name: Stop/update/restart Postgres on {{ inventory_hostname }}
    when:
    - can_upgrade_postgres
    block:
    - include_role: name=postgres/restart
      vars:
        postgres_service_end_state: stopped
    - include_role: name=postgres/update
      vars:
        upgrade_from: '4'
    - include_role: name=postgres/user
    - include_role: name=postgres/config
    - include_role: name=postgres/final

  - name: Create symlink for harp-manager to connect to database
    file:
      name: "/var/run/postgresql/.s.PGSQL.{{ postgres_port }}"
      src: "/var/run/edb-pge/.s.PGSQL.{{ postgres_port }}"
      state: "link"
      force: true
    when: >
      postgres_flavour == 'edbpge'
      and 'bdr' in role

  - name: Unfence the node after upgrade
    include_role:
      name: postgres/bdr
      tasks_from: unfence.yml
    vars:
      failover_manager: harp
    when:
      - "'bdr' in role"
      - inventory_hostname in first_bdr_primary_candidates

  - name: Wait for bdr nodes to reach consensus before proceeding
    postgresql_query:
      conninfo: "{{ dsn|dbname(bdr_database) }}"
      query: >
        select s->>'leader_id' != '0' or s->>'leader' != '0' status from bdr.get_raft_status() s;
    register: bdr_raft
    until: bdr_raft.status == true
    retries: 60
    delay: 1
    become_user: "{{ postgres_user }}"
    become: yes
    when:
    - "'bdr' in role"
    - "'replica' not in role"

  # Ansible won't stop execution if a host becomes unreachable, despite
  # the any_errors_fatal setting. We must detect that situation and fail
  # so that we don't proceed to the next host if something went wrong in
  # upgrading this one.

  - name: Fail if any host became unreachable
    assert:
      msg: "One or more hosts are no longer reachable"
      that:
        ansible_play_hosts == ansible_play_hosts_all

- name: Upgrade pgd-cli
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_bdr:role_pgdcli:&g_update_hosts
  tasks:
  - include_role: name=pgdcli/update
    when:
    - upgrade_selector|strict_selects('pgdcli') or upgrade_selector|strict_selects('all')
    - (('bdr' in role  or 'pgd-proxy' in role) and bdrdb_major_version is version('5', '<=')) or 'pgdcli' in role
    - can_upgrade_pgdcli

- name: Update BDR v5-specific configuration
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_bdr
  tasks:
  - include_role:
      name: postgres/bdr
      tasks_from: update.yml

  - name: Log pgd-cli diagnostic output after BDR group configuration
    include_role:
      name: test
      tasks_from: pgd-cli/info.yml
    when:
      inventory_hostname == first_bdr_primary

  - name: Wait for write leader elections to complete
    command: >
      {{ pgdcli_bin }} show-groups -o json
    register: pgd_show_groups
    become_user: "{{ postgres_user }}"
    become: yes
    vars:
      group_info: "{{ (pgd_show_groups.stdout or '[]')|from_json }}"
      leaderless_routing_groups: >-
        {{ group_info
           |json_query("[?enable_proxy_routing && write_lead == '']") }}
      election_timeout: >-
        {{ cluster_facts.pg_settings["bdr.raft_global_election_timeout"]
           |default(6000) }}
    until:
      pgd_show_groups is not successful
      or leaderless_routing_groups is empty
    retries: "{{ (4*(election_timeout|int)/1000)|int }}"
    delay: 1
    when:
      inventory_hostname == first_bdr_primary

# All harp-proxy instances remain generally available throughout the
# node-by-node process (other than the two brief interruptions when we
# fence the active node). Now we must transfer routing responsibilities
# from harp-proxy to pgd-proxy.

- name: Update proxies in cluster {{ cluster_dir }}
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_harp-proxy:role_pgd-proxy:role_pgbouncer:&g_update_hosts
  tasks:
  - name: Set up pgd-proxy
    include_role:
      name: pgd_proxy
    when: >
      'pgd-proxy' in role

  - name: Stop harp-proxy
    service:
      name: harp-proxy
      state: stopped
    when: >
      'harp-proxy' in role

  - name: Start pgd-proxy
    service:
      name: pgd-proxy
      state: started
    when: >
      'pgd-proxy' in role

  - name: Log pgd-cli diagnostic output
    block:
    - include_role:
        name: test
        tasks_from: pgd-cli/info.yml
    when: >
      'pgd-proxy' in role
    vars:
      with_user: "{{ pgd_proxy_user }}"
    run_once: true

  # pgd-proxy should be correctly routing traffic now.

  - name: Check pgd-proxy status
    include_role:
      name: test
      tasks_from: pgd-proxy/basic.yml
    when: >
      'pgd-proxy' in role

- name: Stop monitoring proxy downtime
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: role_bdr
  tasks:
  - include_role:
      name: test
      tasks_from: proxy-monitor/report.yml
    when:
      inventory_hostname == first_bdr_primary
      and enable_proxy_monitoring

# The node-by-node upgrade process is now complete, and we have replaced
# harp-proxy with pgd-proxy. The cluster should be back to normal now,
# and we can take the time to get rid of harp completely.
#
# We do this cleanup only if the harp config file exists, and we remove
# it afterwards (so that we don't repeat these steps during subsequent
# minor-version upgrades.)
#
# (Note: we don't remove etcd, because we can't be completely sure that
# nobody else was using it.)

- name: Clean up old services in the cluster
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: all
  tasks:

  - name: Check for harp config.yml to determine if cleanup is needed
    stat:
      path: "{{ harp_directory }}/config.yml"
    register: harp_config

  # When we stop harp-manager, it will normally try to stop Postgres,
  # which we obviously don't want. The simplest of many ways to avoid
  # this is to set the cluster as unmanaged and wait for the change to
  # propagate through the DCS before stopping harp-manager.
  #
  # Normally harp-manager should still be running at this point, but we
  # double-check before doing anything, because we want to do the right
  # cleanup even after a failed upgrade is restarted.

  - name: Get rid of harp-manager
    when:
      - "'bdr' in role"
      - harp_config.stat.exists
    block:
    - name: Check if harp-manager is running
      command: pgrep harp-manager
      register: harp_manager_check
      ignore_errors: yes

    - name: Set the cluster to unmanaged before stopping harp-manager
      when:
        harp_manager_check.stdout != ''
      block:

      # In principle, we could run 'harpctl unmanage cluster' on any one
      # node, and just wait for the change to propagate everywhere else,
      # but we're taking no chances here.

      - name: Run 'harpctl unmanage cluster'
        command:
          harpctl -f /etc/harp/config.yml unmanage cluster
        become_user: "{{ postgres_user }}"
        become: yes

      - name: Wait for cluster to become unmanaged
        command:
          harpctl -f /etc/harp/config.yml get cluster -o json
        register: harpctl_get_cluster
        become_user: "{{ postgres_user }}"
        become: yes
        retries: 60
        vars:
          cluster_info: "{{ (harpctl_get_cluster.stdout or '{}')|from_json }}"
        until:
          harpctl_get_cluster is not successful
          or ('is_managed' in cluster_info and not cluster_info.is_managed)

    - name: Ensure that harp-manager is not running
      service:
        name: harp-manager
        state: stopped

    - name: Remove symlink for harp-manager to connect to database
      file:
        name: "/var/run/postgresql/.s.PGSQL.{{ postgres_port }}"
        state: "absent"
      when: >
        postgres_flavour == 'edbpge'
        and 'bdr' in role

    - name: Remove additional harp service definitions
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/systemd/system/harp-manager.service.d/override.conf
        - /etc/systemd/system/harp-manager.service.d
        - /etc/systemd/system/harp-postgres.target

    - name: Disable the harp-manager service
      service:
        name: harp-manager
        enabled: false
        daemon_reload: true

    - name: Remove the harp-manager package
      package:
        name: harp-manager
        state: absent

  # There are no special considerations to removing harp-proxy, which we
  # have already stopped above. We just need to remove the package and
  # disable/remove the service.

  - name: Get rid of harp-proxy
    when: >
      'harp-proxy' in role
      and harp_config.stat.exists
    block:
    - name: Remove additional harp-proxy service definitions
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/systemd/system/harp-proxy.service.d/override.conf
        - /etc/systemd/system/harp-proxy.service.d

    - name: Disable the harp-proxy service
      service:
        name: harp-proxy
        enabled: false
        daemon_reload: true

    - name: Remove the harp-proxy package
      package:
        name: harp-proxy
        state: absent

  - name: Remove harp configuration files after cleanup
    file:
      path: "{{ harp_directory }}"
      state: absent
    when:
      harp_config.stat.exists

- name: Run BDR/PGD-specific health checks after upgrade
  any_errors_fatal: true
  max_fail_percentage: 0
  become_user: root
  become: yes
  environment: "{{ target_environment }}"
  hosts: all
  tasks:
  - name: Run pgd-proxy checks
    include_role:
      name: test
      tasks_from: pgd-proxy/basic.yml
    when: >
      'pgd-proxy' in role

  - name: Log pgd-cli diagnostic output
    include_role:
      name: test
      tasks_from: pgd-cli/info.yml
    vars:
      bdr_version: "{{ bdrdb_major_version }}"
    when:
      - first_bdr_primary is defined
      - inventory_hostname == first_bdr_primary
      - (('bdr' in role  or 'pgd-proxy' in role) and bdrdb_major_version is version('5', '<=')) or 'pgdcli' in role
