---

# © Copyright EnterpriseDB UK Limited 2015-2025 - All rights reserved.

- include_tasks: detect-installed.yml

- name: Ensure EFM is currently installed
  assert:
    that:
    - installed_efm_versions is defined and installed_efm_versions != []
    fail_msg: >
      No version of EFM is installed, nothing to update.

- name: Ensure only one version of EFM is currently installed
  assert:
    that:
    - installed_efm_versions | difference([efm_version]) | length < 2
    fail_msg: >
      More than one version of EFM is installed.
      Found versions: {{ installed_efm_versions | join(', ') }}"
      Please uninstall any currently unused EFM package versions before running 'tpaexec upgrade' again.
