---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

use_ssl_cert_authentication: no

patroni_ssl_service: patroni
patroni_ssl_dir: "/etc/tpa/{{ patroni_ssl_service }}"
patroni_local_ssl_dir: "{{
  use_ssl_cert_authentication|
   ternary(cluster_dir ~ '/ssl', cluster_dir ~ '/ssl/patroni') }}"
