---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- name: Create etcd group
  group:
    name: "{{ etcd_group }}"
  when: >
    'etcd' in role
    and etcd_group != 'root'

- name: Create etcd user
  user:
    name: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    system: yes
    comment: "etcd key-value store"
    home: /var/lib/etcd
    password: '!'
    shell: /bin/nologin
  when: >
    'etcd' in role
    and etcd_user != 'root'

- name: Ensure /etc/etcd exists
  file:
    path: /etc/etcd
    state: directory
    owner: root
    group: root
    mode: "0750"
  when: >
    'etcd' in role

# This password will be used later when setting up authentication. But that occurs only
# once the etcd cluster is up and running, and we want to know the password before-hand,
# allowing it to be used elsewhere before that stage, if needed.
- name: "Generate password for the etcd user root"
  when: >
    'etcd' in role
    and etcd_authentication_mode == 'basic'
  include_role:
    name: secret
  vars:
    secret_name: etcd_root_password
    generate_password: true

- block:
  - include_tasks: ssl.yml

  # Refresh facts so etcdctl_options is properly set with the SSL parameters, if any
  - name: Refresh etcd facts
    include_role:
      name: etcd/facts
  when: >
    'etcd' in role
    and etcd_ssl_enabled

- name: Install etcd.conf
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Note etcd restart required
  when: >
    'etcd' in role

- name: Ensure etcd data files have correct ownership
  file:
    dest: /var/lib/etcd
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    recurse: yes
  notify:
    - Note etcd restart required
