#!/bin/bash

IFS=
set -e -u

TOP=$(dirname $0)/..
type realpath &>/dev/null && TOP=$(realpath $TOP)

# If you invoke ansible directly (i.e. not through this script), you
# must set ANSIBLE_CONFIG as below.
#
# Set ANSIBLE_CONFIG, ANSIBLE_LOG_PATH, and ANSIBLE_INVENTORY to our
# versions if they are not already set.

export ANSIBLE_CONFIG=${ANSIBLE_CONFIG:-TOP/ansible.cfg}
export ANSIBLE_LOG_PATH=${ANSIBLE_LOG_PATH:-$TOP/ansible.log}
export ANSIBLE_INVENTORY=${ANSIBLE_INVENTORY:-$TOP/inventory/static}

# Append our directories to various search paths.

export ANSIBLE_LIBRARY=${ANSIBLE_LIBRARY:+$ANSIBLE_LIBRARY:}$TOP/library
export ANSIBLE_ROLES_PATH=${ANSIBLE_ROLES_PATH:+$ANSIBLE_ROLES_PATH:}$TOP/roles
export ANSIBLE_FILTER_PLUGINS=${ANSIBLE_FILTER_PLUGINS:+$ANSIBLE_FILTER_PLUGINS:}$TOP/lib/filter_plugins
export ANSIBLE_LOOKUP_PLUGINS=${ANSIBLE_LOOKUP_PLUGINS:+$ANSIBLE_LOOKUP_PLUGINS:}$TOP/lib/lookup_plugins
export ANSIBLE_TEST_PLUGINS=${ANSIBLE_TEST_PLUGINS:+$ANSIBLE_TEST_PLUGINS:}$TOP/lib/test_plugins

# This script may be invoked through symlinks as ansible, ansible-vault,
# or ansible-playbook. If the requested command is already in the PATH,
# we assume that everything's set up properly to run it. Otherwise, we
# expect ANSIBLE_HOME to point to a git checkout and do approximately
# what hacking/env-setup would do.

NEWPATH=$PATH
cmd=$(basename $0)
if ! which $cmd >/dev/null 2>&1; then
    ansidir=${ANSIBLE_HOME:-""}
    if [ -z "$ansidir" ]; then
        echo "Please set ANSIBLE_HOME=/path/to/ansible/dir" 1>&2
        exit
    fi

    if [ ! -x "$ansidir/bin/ansible" ]; then
        echo "Can't find $ansidir/bin/ansible" 1>&2
        exit
    fi

    export PYTHONPATH=$ansidir/lib:${PYTHONPATH:-""}

    NEWPATH="$ansidir/bin:$PATH"
    cmd="$ansidir/bin/$cmd"
fi

PATH="$NEWPATH" $cmd "$@"
