#!/bin/sh

IFS=
set -e -u

utils=$(dirname $0)

cluster=${1:?No cluster specified}
shift

for d in ./clusters/$cluster $utils/../clusters/$cluster; do
    if [ -d $d ]; then
        cluster_dir=$d
    fi
done

if [ -z ${cluster_dir+x} ]; then
    echo "Can't find directory clusters/$cluster"
    exit
fi

$utils/ansible-playbook \
    $cluster_dir/deploy.yml \
    -i $cluster_dir/inventory \
    -e cluster=$cluster_dir "$@"
