#!/bin/sh

IFS=
set -e -u

utils=$(dirname $0)

cluster=${1:?No cluster specified}
shift

cluster_dir=$utils/../clusters/$cluster
if [ ! -d $cluster_dir ]; then
    echo "Can't find directory clusters/$cluster"
    exit
fi

$utils/ansible-playbook \
    $cluster_dir/deploy.yml \
    -i $cluster_dir/inventory \
    -e ansible_ssh_common_args="\"-o UserKnownHostsFile='$cluster_dir/known_hosts'\"" \
    -e cluster=$cluster_dir "$@"
