#!/bin/sh

IFS=
set -e -u

utils=$(dirname $0)

cluster=${1:?No cluster specified}
shift

cluster_dir=$(realpath $utils/../clusters/$cluster)
if [ ! -d $cluster_dir ]; then
    echo "Can't find directory clusters/$cluster"
    exit
fi

$utils/ansible-playbook \
    $utils/../platforms/aws/provision.yml \
    -i $cluster_dir/inventory \
    -e cluster=$cluster_dir "$@"
