---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

efm_conf_settings: {}
efm_bind_by_hostname: false

# Retry settings for efm cluster-status command. The default is 5 minutes.
efm_cluster_status_retries: 60
efm_cluster_status_retry_delay: 5

# User settings that give the EFM user the superuser role
efm_user_is_superuser: true
default_efm_role_attrs:
  - NOSUPERUSER
  - NOCREATEDB
  - NOLOGIN