---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- name: Stop/update/restart pgbouncer
  when: >
    'pgbouncer' in role
  block:
  - include_role: name=pgbouncer/restart
    vars:
      pgbouncer_service_end_state: stopped

  - include_role: name=pgbouncer/pkg
    vars:
      allow_package_upgrades: yes

  - include_role:
      name: pgbouncer/config
  
  - name: "Ensure pgbouncer.log is owned by {{ postgres_user }}"
    file:
      path: /var/log/pgbouncer/pgbouncer.log
      owner: "{{ postgres_user }}"
      group: "{{ postgres_group }}"
      mode: "0644"
      state: file
    when: log_server is not defined

  - include_role: name=pgbouncer/restart
    vars:
      pgbouncer_service_end_state: started
