---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- include_tasks: list-packages.yml
  vars:
    list_varname: _all_pem_server_packages

- name: Check if we can install the desired edb-pem packages
  include_role:
    name: pkg/install
  vars:
    package_list_name: "pem-server packages"
    package_list: "{{ _all_pem_server_packages }}"
    check_install_only: yes
    result_varname: pem_server_pkg_check

- assert:
    that: pem_server_pkg_check is successful
    fail_msg: >
      Some packages are missing or the 'pem_server_package_version' specified in 'config.yml' cannot be satisfied.

- debug:
    msg: "The desired 'pem_server_package_version' or higher is already installed. PEM server upgrade tasks will be skipped on '{{ inventory_hostname }}'."
  when: pem_server_pkg_check.changed is false

- set_fact:
    pem_server_package_update: "{{
      pem_server_pkg_check is defined 
      and pem_server_pkg_check is successful
      and pem_server_pkg_check.changed is true
    }}"