---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- name: Include pgdcli-pre-update hook
  include_tasks: "{{ hook }}"
  when:
    lookup('first_found', dict(files=hook, skip=True))
  vars:
    hook: "{{ cluster_dir }}/hooks/pgdcli-pre-update.yml"

- name: Upgrade pgdcli package
  include_role:
    name: pgdcli
    tasks_from: upgrade.yml

- name: Include pgdcli-post-update hook
  include_tasks: "{{ hook }}"
  when:
    lookup('first_found', dict(files=hook, skip=True))
  vars:
    hook: "{{ cluster_dir }}/hooks/pgdcli-post-update.yml"