#!/usr/bin/env bash

#
# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.
#
#

num=$1

hostnames=(
    one
    two
    three
    four
    five
    six
    seven
    eight
    nine
    ten
)

printf '%s\n' "${hostnames[@]:0:$num}"
