#!/bin/bash
#
# Runs ansible in the context of a cluster—i.e., with the correct path
# to the cluster's inventory and so on. This is for ad-hoc commands, not
# to run playbooks; see also ansible-cluster-playbook.
#
# Example: utils/ansible-cluster test/tpa all -m ping

IFS=
set -e -u

utils=$(dirname $0)

cluster=${1:?No cluster specified}
shift

cluster_dir=$cluster
if [[ ${cluster_dir:0:1} != '/' ]]; then
    clusters=$(realpath $utils/../clusters);
    cluster=$(echo $cluster|sed 's,^clusters/,,')
    cluster_dir="$clusters/$cluster"
fi

if [ ! -d $cluster_dir ]; then
    echo "Can't find directory $cluster_dir"
    exit
fi

$utils/ansible \
    -i $cluster_dir/inventory \
    --vault-password-file $cluster_dir/vault/vault_pass.txt \
    -e cluster=$cluster_dir "$@"
