#!/bin/bash
#
# Runs ansible in the context of a cluster—i.e., with the correct path
# to the cluster's inventory and so on. This is for ad-hoc commands, not
# to run playbooks; see also ansible-cluster-playbook.
#
# Example: utils/ansible-cluster test/tpa all -m ping

IFS=
set -e -u

utils=$(dirname $0)

cluster=${1:?No cluster specified}
cluster=$(echo $cluster|sed 's,^clusters/,,')
shift

clusters=$(realpath $utils/../clusters);

arg="$clusters/$cluster"

if [ -d $arg ]; then
    cluster_dir=$arg
else
    echo "Can't find directory clusters/$cluster"
    exit
fi

$utils/ansible \
    -i $cluster_dir/inventory \
    --vault-password-file $cluster_dir/vault/vault_pass.txt \
    -e cluster=$cluster_dir "$@"
