#!/bin/bash
#
# Provisions a cluster according to config.yml

IFS=
set -e -u

utils=$(dirname $0)

cluster=${1:?No cluster specified}
shift

cluster_dir=$cluster
if [[ ${cluster_dir:0:1} != '/' ]]; then
    clusters=$(realpath $utils/../clusters);
    cluster=$(echo $cluster|sed 's,^clusters/,,')
    cluster_dir="$clusters/$cluster"
fi

if [ ! -d $cluster_dir ]; then
    echo "Can't find directory $cluster_dir"
    exit
fi

$utils/ansible-playbook \
    $utils/../platforms/aws/provision.yml \
    -e cluster=$cluster_dir "$@"
