# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

"""Behavioural tests for the merge-arch-hashes post-processor.

The script under test lives at
.github/actions/update-requirements/add_arch_hashes_to_requirements_files.py
and is not part of an importable package, so we load it via importlib.
These tests lock in the observable contract (parse, render, round-trip)
before the script is refactored.
"""

import importlib.util
import re
import textwrap
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = (
    REPO_ROOT
    / ".github"
    / "actions"
    / "update-requirements"
    / "add_arch_hashes_to_requirements_files.py"
)


def _load_module():
    spec = importlib.util.spec_from_file_location("add_arch_hashes", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def aah():
    return _load_module()


SAMPLE_FILE = textwrap.dedent(
    """\
    #
    # This file is autogenerated by pip-compile with Python 3.12
    # by the following command:
    #
    #    pip-compile --generate-hashes --output-file=requirements.txt requirements.in
    #
    ansible-core==2.16.17 \\
        --hash=sha256:ff3a59611d85778fc6ffc8f007b5c80fa4950f08784812fdb7c5b590f6a0d88a \\
        --hash=sha256:19ae102b166f9c2d01461eebd2ce81458626a0727557089463d4f241f5d578f3
        # via -r requirements.in
    botocore==1.42.69 \\
        --hash=sha256:ef0e3d860a5d7bffc0ccb4911781c4c27d538557ed9a616ba1926c762d72e5f6 \\
        --hash=sha256:0934f2d90403c5c8c2cba83e754a39d77edcad5885d04a79363edff3e814f55e
        # via
        #   boto3
        #   s3transfer
    """
)

ANSIBLE_HASHES = {
    "ff3a59611d85778fc6ffc8f007b5c80fa4950f08784812fdb7c5b590f6a0d88a",
    "19ae102b166f9c2d01461eebd2ce81458626a0727557089463d4f241f5d578f3",
}
BOTOCORE_HASHES = {
    "ef0e3d860a5d7bffc0ccb4911781c4c27d538557ed9a616ba1926c762d72e5f6",
    "0934f2d90403c5c8c2cba83e754a39d77edcad5885d04a79363edff3e814f55e",
}


def _write_sample(tmp_path):
    f = tmp_path / "requirements.txt"
    f.write_text(SAMPLE_FILE)
    return f


def test_parse_extracts_deps(aah, tmp_path):
    f = _write_sample(tmp_path)
    result = aah.parse_requirements([str(f)])

    assert list(result.keys()) == [str(f)]
    deps = result[str(f)]["deps"]
    assert set(deps.keys()) == {"ansible-core", "botocore"}
    assert deps["ansible-core"]["version"] == "2.16.17"
    assert deps["ansible-core"]["hash_set"] == ANSIBLE_HASHES
    assert deps["botocore"]["version"] == "1.42.69"
    assert deps["botocore"]["hash_set"] == BOTOCORE_HASHES


def test_parse_captures_via_comment(aah, tmp_path):
    f = _write_sample(tmp_path)
    deps = aah.parse_requirements([str(f)])[str(f)]["deps"]
    assert deps["ansible-core"]["comment"] == ["# via -r requirements.in"]
    assert deps["botocore"]["comment"] == ["# via", "#   boto3", "#   s3transfer"]


def test_parse_captures_header(aah, tmp_path):
    f = _write_sample(tmp_path)
    header = aah.parse_requirements([str(f)])[str(f)]["comment_header"]
    assert header[0] == "#\n"
    assert any("autogenerated by pip-compile" in line for line in header)


def test_render_produces_sorted_hashes(aah, tmp_path, monkeypatch):
    f = _write_sample(tmp_path)
    parsed = aah.parse_requirements([str(f)])

    monkeypatch.chdir(REPO_ROOT)
    aah._render_template(parsed)
    rendered = f.read_text()

    for block in re.split(r"\n(?=[A-Za-z0-9])", rendered):
        hashes = re.findall(r"--hash=sha256:([a-f0-9]+)", block)
        if hashes:
            assert hashes == sorted(hashes), (
                f"hashes not alphabetical in block: {block.splitlines()[0]!r}"
            )


def test_render_is_deterministic(aah, tmp_path, monkeypatch):
    f = _write_sample(tmp_path)
    monkeypatch.chdir(REPO_ROOT)

    aah._render_template(aah.parse_requirements([str(f)]))
    first = f.read_text()
    aah._render_template(aah.parse_requirements([str(f)]))
    second = f.read_text()

    assert first == second


def test_round_trip_preserves_deps(aah, tmp_path, monkeypatch):
    f = _write_sample(tmp_path)
    monkeypatch.chdir(REPO_ROOT)

    before = aah.parse_requirements([str(f)])[str(f)]["deps"]
    aah._render_template({str(f): {"comment_header": [], "deps": before}})
    after = aah.parse_requirements([str(f)])[str(f)]["deps"]

    assert set(before.keys()) == set(after.keys())
    for name in before:
        assert before[name]["version"] == after[name]["version"]
        assert before[name]["hash_set"] == after[name]["hash_set"]
