# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

"""Behavioural tests for the merge-arch-hashes post-processor.

The script under test lives at
.github/actions/update-requirements/add_arch_hashes_to_requirements_files.py
and is not part of an importable package, so we load it via importlib.
These tests lock in the observable contract (parse, render, round-trip)
before the script is refactored.
"""

import importlib.util
import re
import textwrap
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = (
    REPO_ROOT
    / ".github"
    / "actions"
    / "update-requirements"
    / "add_arch_hashes_to_requirements_files.py"
)


def _load_module():
    spec = importlib.util.spec_from_file_location("add_arch_hashes", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def aah():
    return _load_module()


SAMPLE_FILE = textwrap.dedent(
    """\
    #
    # This file is autogenerated by pip-compile with Python 3.12
    # by the following command:
    #
    #    pip-compile --generate-hashes --output-file=requirements.txt requirements.in
    #
    ansible-core==2.16.17 \\
        --hash=sha256:ff3a59611d85778fc6ffc8f007b5c80fa4950f08784812fdb7c5b590f6a0d88a \\
        --hash=sha256:19ae102b166f9c2d01461eebd2ce81458626a0727557089463d4f241f5d578f3
        # via -r requirements.in
    botocore==1.42.69 \\
        --hash=sha256:ef0e3d860a5d7bffc0ccb4911781c4c27d538557ed9a616ba1926c762d72e5f6 \\
        --hash=sha256:0934f2d90403c5c8c2cba83e754a39d77edcad5885d04a79363edff3e814f55e
        # via
        #   boto3
        #   s3transfer
    """
)

ANSIBLE_HASHES = {
    "ff3a59611d85778fc6ffc8f007b5c80fa4950f08784812fdb7c5b590f6a0d88a",
    "19ae102b166f9c2d01461eebd2ce81458626a0727557089463d4f241f5d578f3",
}
BOTOCORE_HASHES = {
    "ef0e3d860a5d7bffc0ccb4911781c4c27d538557ed9a616ba1926c762d72e5f6",
    "0934f2d90403c5c8c2cba83e754a39d77edcad5885d04a79363edff3e814f55e",
}


def _write_sample(tmp_path):
    f = tmp_path / "requirements.txt"
    f.write_text(SAMPLE_FILE)
    return f


def test_parse_extracts_deps(aah, tmp_path):
    f = _write_sample(tmp_path)
    result = aah.parse_requirements([str(f)])

    assert list(result.keys()) == [str(f)]
    deps = result[str(f)]["deps"]
    assert set(deps.keys()) == {"ansible-core", "botocore"}
    assert deps["ansible-core"]["version"] == "2.16.17"
    assert deps["ansible-core"]["hash_set"] == ANSIBLE_HASHES
    assert deps["botocore"]["version"] == "1.42.69"
    assert deps["botocore"]["hash_set"] == BOTOCORE_HASHES


def test_parse_captures_via_comment(aah, tmp_path):
    f = _write_sample(tmp_path)
    deps = aah.parse_requirements([str(f)])[str(f)]["deps"]
    assert deps["ansible-core"]["comment"] == ["# via -r requirements.in"]
    assert deps["botocore"]["comment"] == ["# via", "#   boto3", "#   s3transfer"]


def test_parse_captures_header(aah, tmp_path):
    f = _write_sample(tmp_path)
    header = aah.parse_requirements([str(f)])[str(f)]["comment_header"]
    assert header[0] == "#\n"
    assert any("autogenerated by pip-compile" in line for line in header)


def test_render_produces_sorted_hashes(aah, tmp_path, monkeypatch):
    f = _write_sample(tmp_path)
    parsed = aah.parse_requirements([str(f)])

    monkeypatch.chdir(REPO_ROOT)
    aah._render_template(parsed)
    rendered = f.read_text()

    for block in re.split(r"\n(?=[A-Za-z0-9])", rendered):
        hashes = re.findall(r"--hash=sha256:([a-f0-9]+)", block)
        if hashes:
            assert hashes == sorted(hashes), (
                f"hashes not alphabetical in block: {block.splitlines()[0]!r}"
            )


def test_render_is_deterministic(aah, tmp_path, monkeypatch):
    f = _write_sample(tmp_path)
    monkeypatch.chdir(REPO_ROOT)

    aah._render_template(aah.parse_requirements([str(f)]))
    first = f.read_text()
    aah._render_template(aah.parse_requirements([str(f)]))
    second = f.read_text()

    assert first == second


def _dep(version, hashes):
    return {"name": "x", "version": version, "hash_set": set(hashes), "comment": []}


def test_merge_unions_hashes_on_name_and_version_match(aah):
    actual_deps = {
        "requirements.txt": {
            "comment_header": [],
            "deps": {"pkg": _dep("1.0", ["a"])},
        }
    }
    target = _dep("1.0", ["b"])

    matched = aah._merge_into_actuals("pkg", target, actual_deps)

    assert matched is True
    assert actual_deps["requirements.txt"]["deps"]["pkg"]["hash_set"] == {"a", "b"}


def test_merge_skips_on_version_mismatch(aah):
    actual_deps = {
        "requirements.txt": {
            "comment_header": [],
            "deps": {"pkg": _dep("1.0", ["a"])},
        }
    }
    target = _dep("2.0", ["b"])

    matched = aah._merge_into_actuals("pkg", target, actual_deps)

    assert matched is False
    assert actual_deps["requirements.txt"]["deps"]["pkg"]["hash_set"] == {"a"}


def test_merge_skips_on_missing_name(aah):
    actual_deps = {
        "requirements.txt": {
            "comment_header": [],
            "deps": {"other": _dep("1.0", ["a"])},
        }
    }
    target = _dep("1.0", ["b"])

    matched = aah._merge_into_actuals("pkg", target, actual_deps)

    assert matched is False
    assert actual_deps["requirements.txt"]["deps"]["other"]["hash_set"] == {"a"}


def test_round_trip_preserves_deps(aah, tmp_path, monkeypatch):
    f = _write_sample(tmp_path)
    monkeypatch.chdir(REPO_ROOT)

    before = aah.parse_requirements([str(f)])[str(f)]["deps"]
    aah._render_template({str(f): {"comment_header": [], "deps": before}})
    after = aah.parse_requirements([str(f)])[str(f)]["deps"]

    assert set(before.keys()) == set(after.keys())
    for name in before:
        assert before[name]["version"] == after[name]["version"]
        assert before[name]["hash_set"] == after[name]["hash_set"]


# ---- end-to-end stdout contract: feeds the CI hash_check step ----
#
# The CI action captures this script's stdout into $GITHUB_OUTPUT.ERRORS;
# non-empty ERRORS forces the PR open as draft (action.yml: `draft: ${{
# steps.hash_check.conclusion == 'failure' }}`) and puts the diagnostic
# into the PR body.

ACTUALS_ONE_DEP = textwrap.dedent(
    """\
    #
    # header
    #
    kept==1.0 \\
        --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        # via -r requirements.in
    """
)

ARCH_MATCHING = textwrap.dedent(
    """\
    #
    # header
    #
    kept==1.0 \\
        --hash=sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        # via -r requirements-ppc64le.in
    """
)

ARCH_MISSING_DEP = textwrap.dedent(
    """\
    #
    # header
    #
    notinactuals==1.0 \\
        --hash=sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        # via -r requirements-ppc64le.in
    """
)

ARCH_VERSION_SKEW = textwrap.dedent(
    """\
    #
    # header
    #
    kept==2.0 \\
        --hash=sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        # via -r requirements-ppc64le.in
    """
)


def _seed_arch_inputs(tmp_path, ppc64le, s390x):
    (tmp_path / "requirements.txt").write_text(ACTUALS_ONE_DEP)
    (tmp_path / "requirements-ppc64le.txt").write_text(ppc64le)
    (tmp_path / "requirements-s390x.txt").write_text(s390x)


def test_add_hashes_silent_when_all_match(aah, tmp_path, monkeypatch, capsys):
    _seed_arch_inputs(tmp_path, ARCH_MATCHING, ARCH_MATCHING)
    monkeypatch.chdir(tmp_path)

    aah.add_hashes("")

    assert capsys.readouterr().out == ""


def test_add_hashes_reports_dep_missing_from_actuals(
    aah, tmp_path, monkeypatch, capsys
):
    _seed_arch_inputs(tmp_path, ARCH_MISSING_DEP, ARCH_MISSING_DEP)
    monkeypatch.chdir(tmp_path)

    aah.add_hashes("")

    out = capsys.readouterr().out
    assert out.strip(), "expected diagnostic on stdout to fail hash_check step"
    assert "notinactuals==1.0" in out
    assert "    --hash=sha256:cccc" in out
    assert "could not be matched in requirements.txt" in out


def test_add_hashes_reports_version_skew(aah, tmp_path, monkeypatch, capsys):
    _seed_arch_inputs(tmp_path, ARCH_VERSION_SKEW, ARCH_VERSION_SKEW)
    monkeypatch.chdir(tmp_path)

    aah.add_hashes("")

    out = capsys.readouterr().out
    assert "kept==2.0" in out
    assert "could not be matched in requirements.txt" in out


def test_add_hashes_reports_per_arch_file(aah, tmp_path, monkeypatch, capsys):
    # ppc64le matches, s390x has a missing dep — only s390x's mismatch
    # should trigger output.
    _seed_arch_inputs(tmp_path, ARCH_MATCHING, ARCH_MISSING_DEP)
    monkeypatch.chdir(tmp_path)

    aah.add_hashes("")

    out = capsys.readouterr().out
    assert "notinactuals==1.0" in out
    # Exactly one diagnostic — kept matched in ppc64le and the union
    # carried into actuals satisfies s390x's kept entry too.
    assert out.count("could not be matched") == 1


def test_add_hashes_diagnostic_has_no_python_reprs(
    aah, tmp_path, monkeypatch, capsys
):
    """The diagnostic ends up in the PR body verbatim; no leaky Python
    repr (set, dict_keys) should surface there."""
    _seed_arch_inputs(tmp_path, ARCH_MISSING_DEP, ARCH_MISSING_DEP)
    monkeypatch.chdir(tmp_path)

    aah.add_hashes("")

    out = capsys.readouterr().out
    assert "dict_keys" not in out
    assert "{'" not in out
    assert "set()" not in out
