#!/bin/bash
#
# Synopsis:
#
# clusters/images/build-images [-r] [PGDG|2ndQPostgres|…] [9.5|9.6|…]

IFS=
set -e -u

TOP=$(dirname $0)/../..
type realpath &>/dev/null && TOP=$(realpath $TOP)
export TPA_DIR=${TPA_DIR:-$TOP}

if [ ! -d $TPA_DIR/clusters/images ]; then
    echo "Please run clusters/images/build-images (from the TPA directory)"
    exit
fi

reconfig=0
opt=${1:-""}
if [ "$opt" = "-r" ]; then
    reconfig=1
    shift
fi

variant=${1:-"PGDG"}
version=${2:-"10"}
suffix=${3:-""}

test $reconfig = 1 && \
    $TPA_DIR/ansible/ansible-playbook clusters/images/generate-config.yml

$TPA_DIR/bin/provision images -v

$TPA_DIR/bin/ansible-cluster-playbook images/deploy-$variant.yml -T120 -v \
    -e postgres_variant=$variant -e postgres_version=$version -e suffix=$suffix
$TPA_DIR/bin/ansible-cluster-playbook images/generate-amis.yml -v \
    -e postgres_variant=$variant -e postgres_version=$version -e suffix=$suffix

$TPA_DIR/bin/deprovision images -v
