#!/bin/bash
#
# Synopsis:
#
# clusters/images/build-images [-r] [PGDG|2ndQPostgres|…] [9.5|9.6|…]

IFS=
set -e -u

if [ ! -d clusters/images ]; then
    echo "Please run clusters/images/build-images (from the TPA directory)"
    exit
fi

reconfig=0
opt=${1:-""}
if [ "$opt" = "-r" ]; then
    reconfig=1
    shift
fi

variant=${1:-"PGDG"}
version=${2:-"9.6"}
suffix=${3:-"$(date +%Y%m%d)"}

test $reconfig = 1 && \
    utils/ansible-playbook clusters/images/generate-config.yml
utils/provision images -v

# Wait for a while for the instances to replace their SSH host keys.
sleep 120

utils/ansible-cluster-playbook images/deploy-$variant.yml -T120 -v \
    -e postgres_variant=$variant -e postgres_version=$version -e suffix=$suffix
utils/ansible-cluster-playbook images/generate-amis.yml -v \
    -e postgres_variant=$variant -e postgres_version=$version -e suffix=$suffix

utils/deprovision images -v
