#!/bin/bash
# Copyright © 2ndQuadrant Limited <info@2ndquadrant.com>
#
# This is a wrapper for bin/ansible that sets various environment
# variables before invoking the real executable (which must be under
# ANSIBLE_HOME or in PATH).

IFS=$' \t\n'
set -eu

# If $TPA_DIR is not already set, we guess TPA_DIR based on $0 (so that
# a git checkout takes precedence over a package installation), or use
# /opt/2ndQuadrant/TPA if it exists.

TOP=/opt/2ndQuadrant/TPA
if [[ -z "${TPA_DIR:-}" ]]; then
    SRC=$(dirname $0)/..
    type realpath &>/dev/null && SRC=$(realpath $SRC)
    if [[ -d $SRC/roles ]]; then
        TOP=$SRC
    fi
fi

export TPA_DIR=${TPA_DIR:-$TOP}

# If we can find a virtualenv located relative to TPA_DIR, we activate
# it as a convenience.

if [[ -f $TPA_DIR/tpa-virtualenv/bin/activate ]]; then
    set +u
    source $TPA_DIR/tpa-virtualenv/bin/activate
    set -u
fi

# Set ANSIBLE_LOG_PATH, ANSIBLE_CONFIG, and ANSIBLE_INVENTORY to our
# versions if they are not already set.

export ANSIBLE_LOG_PATH=${ANSIBLE_LOG_PATH:-./ansible.log}
export ANSIBLE_CONFIG=${ANSIBLE_CONFIG:-$TPA_DIR/ansible/ansible.cfg}
export ANSIBLE_INVENTORY=${ANSIBLE_INVENTORY:-$TPA_DIR/ansible/hosts}

# Append our directories to various search paths.
#
# In exceptional situations, this allows you to do things like set
# ANSIBLE_ROLES_PATH to override a specific TPAexec-provided role.

export ANSIBLE_LIBRARY=${ANSIBLE_LIBRARY:+$ANSIBLE_LIBRARY:}$TPA_DIR/library
export ANSIBLE_ROLES_PATH=${ANSIBLE_ROLES_PATH:+$ANSIBLE_ROLES_PATH:}$TPA_DIR/roles
export ANSIBLE_TEST_PLUGINS=${ANSIBLE_TEST_PLUGINS:+$ANSIBLE_TEST_PLUGINS:}$TPA_DIR/lib/test_plugins
export ANSIBLE_ACTION_PLUGINS=${ANSIBLE_ACTION_PLUGINS:+$ANSIBLE_ACTION_PLUGINS:}$TPA_DIR/lib/action_plugins
export ANSIBLE_FILTER_PLUGINS=${ANSIBLE_FILTER_PLUGINS:+$ANSIBLE_FILTER_PLUGINS:}$TPA_DIR/lib/filter_plugins
export ANSIBLE_LOOKUP_PLUGINS=${ANSIBLE_LOOKUP_PLUGINS:+$ANSIBLE_LOOKUP_PLUGINS:}$TPA_DIR/lib/lookup_plugins
export ANSIBLE_CALLBACK_PLUGINS=${ANSIBLE_CALLBACK_PLUGINS:+$ANSIBLE_CALLBACK_PLUGINS:}$TPA_DIR/lib/callback_plugins

# This script may be invoked through symlinks as ansible, ansible-vault,
# or ansible-playbook. If ANSIBLE_HOME is set, we expect it to point to
# a git checkout, and do approximately what hacking/env-setup would do.
# Otherwise, we just try to run ansible.

NEWPATH=$PATH
cmd=$(basename $0)

if [[ -n "${ANSIBLE_HOME:-}" ]]; then
    ansidir=$ANSIBLE_HOME
    if [ ! -x "$ansidir/bin/ansible" ]; then
        echo "ERROR: can't find $ansidir/bin/ansible" 1>&2
        exit 1
    fi

    export PYTHONPATH=$ansidir/lib:${PYTHONPATH:-""}

    NEWPATH="$ansidir/bin:$PATH"
    cmd="$ansidir/bin/$cmd"
fi

PATH="$NEWPATH" $cmd "$@"
