---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- name: Include pg-backup-api-pre-update hook
  include_tasks: "{{ hook }}"
  when:
    lookup('first_found', dict(files=hook, skip=True))
  vars:
    hook: "{{ cluster_dir }}/hooks/pg-backup-api-pre-update.yml"

- name: Upgrade pg-backup-api package
  include_role: name=pgbackupapi/pkg
  vars:
    allow_package_upgrades: yes

- name: Include pg-backup-api-post-update hook
  include_tasks: "{{ hook }}"
  when:
    lookup('first_found', dict(files=hook, skip=True))
  vars:
    hook: "{{ cluster_dir }}/hooks/pg-backup-api-post-update.yml"
