---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- name: Ensure ssl directory exists
  file:
    path: "{{ haproxy_ssl_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

# generate client CA if we don't use one yet for server certs
- name: Generate CA.crt if using selfsigned server certs
  include_role:
    name: sys/ssl/ca
  when:
    not use_ssl_cert_authentication

# push global CA.crt or dedicated one created in previous task
- name: Push CA cert to the node
  copy:
    src: "{{ ssl_ca_file }}"
    remote_src: yes
    dest: "{{ haproxy_ssl_dir }}/CA.crt"
    mode: "0644"
    owner: root
    group: root

# Server certificate
- name: Generate webserver SSL artifacts
  include_role:
    name: sys/ssl/server
  vars:
    ssl_user: root
    ssl_group: root
    ssl_dir: "{{ haproxy_ssl_dir }}"
    ssl_service: "{{ haproxy_ssl_service }}"
    check_result_varname: "haproxy"
    legacy_ssl_enabled: false

# The combined certificate contains both the certificate and the key, as that's what is
# expected by the haproxy daemon when configuring it
- name: Create the combined certificate file for HAProxy
  block:
    - name: Read the certificate file content
      slurp:
        src: "{{ haproxy_ssl_cert_file }}"
      register: cert_content

    - name: Read the private key file content
      slurp:
        src: "{{ haproxy_ssl_key_file }}"
      register: key_content

    - name: Set fact with the combined certificate path for haproxy
      set_fact:
        haproxy_ssl_cert_combined_file: "{{ haproxy_ssl_dir }}/{{ haproxy_ssl_service }}_combined.crt"

    - name: Combine cert and key and write to the destination file
      copy:
        # The `content` parameter takes the two slurped file contents,
        # decodes them from base64, and concatenates them with the '~' operator.
        content: "{{ (cert_content.content | b64decode) ~ (key_content.content | b64decode) }}"
        dest: "{{ haproxy_ssl_cert_combined_file }}"
        owner: root
        group: root
        # The combined file contains a private key, so it should be protected.
        mode: '0600'
