---

# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

- include_tasks: list-packages.yml
  vars:
    list_varname: _all_postgres_packages

# Since new RPM PGD packages might conflict with the existing ones in place in RHEL,
# they need to have the 'allowerasing' flag on place so we don't receive a "Depsolve Error". 

- name: Check if we can install the latest Postgres packages
  include_role:
    name: pkg/install
  vars:
    package_list_name: "postgres packages"
    package_list: "{{ _all_postgres_packages }}"
    force_resolution: "{{ 
        ansible_os_family == 'SUSE' 
        }}"
    allowerasing: "{{
        ansible_os_family == 'RedHat' 
        }}"
    check_install_only: yes
    result_varname: postgres_pkg_check

# The purpose of this check is to warn the user as early as possible if
# they are missing any packages that we would try to install during an
# upgrade window.
#
# Unfortunately, with the way RPM package dependencies work, if new bdr5
# packages ARE present, the check fails with a "Depsolve Error", which
# tells us only that bdr5 packages conflict with the bdr4 ones. That's
# not actually an error, and we shouldn't bother the user with it.

- assert:
    that: postgres_pkg_check is successful
    fail_msg: >
      Some packages are missing or the 'postgres_package_version' specified in 'config.yml' cannot be satisfied.

- debug:
    msg: "The desired 'postgres_package_version' or higher is already installed. Postgres upgrade tasks will be skipped on '{{ inventory_hostname }}'."
  when: postgres_pkg_check.changed is false

- set_fact:
    postgres_package_update: "{{
      postgres_pkg_check is defined 
      and postgres_pkg_check is successful
      and postgres_pkg_check.changed is true
    }}"
