# © Copyright EnterpriseDB UK Limited 2015-2025 - All rights reserved.


name: Ansible collection update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * MON" # 1:00 AM each Monday

env:
  GITHUB_TOKEN: ${{ secrets.GH_SLONIK }}
  LANG: C.UTF-8
  LC_ALL: C.UTF-8

jobs:

  collection-list:
    name: Prepare to check collections
    runs-on: ubuntu-latest
    outputs:
      collection_list: ${{ steps.list-collections.outputs.collections }}
    steps:
      - name: Checkout source repository
        id: checkout-source
        uses: actions/checkout@v6
        with:
          repository: EnterpriseDB/tpa-internal
          token: ${{ env.GITHUB_TOKEN }}

      - name: Get list of collections
        id: list-collections
        run: |
          {
            echo 'collections<<EOF'
            yq -o json '[.collections[] | .name]' collections/requirements.yml
            echo EOF
          } >> $GITHUB_OUTPUT


  main:
    name: Check collections
    runs-on: ubuntu-latest
    needs: collection-list
    strategy:
      fail-fast: false
      matrix:
        collection: ${{ fromJSON(needs.collection-list.outputs.collection_list) }}

    steps:
      - name: Checkout source repository
        id: checkout-source
        uses: actions/checkout@v6
        with:
          repository: EnterpriseDB/tpa-internal
          token: ${{ env.GITHUB_TOKEN }}

      - name: Check for update of ${{ matrix.collection }}
        id: update-check
        run: |
          export FLAG_FILE="$RUNNER_TEMP/update_flag"
          export CHANGELOG_PATH="$RUNNER_TEMP/changelog"

          chmod 755 ./.github/scripts/check_one_collection.sh
          ./.github/scripts/check_one_collection.sh "${{ matrix.collection }}"

          if [ $(cat $FLAG_FILE) == "true" ]; then
            echo "changelog=$(cat $CHANGELOG_PATH)" >> $GITHUB_OUTPUT
          fi
          echo "changed=$(cat $FLAG_FILE)" >> $GITHUB_OUTPUT

      - name: Create pull request
        if: ${{ steps.update-check.outputs.changed == 'true' }}
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          token: ${{ env.GITHUB_TOKEN }}
          signoff: false
          branch: bot/update-${{ matrix.collection }}
          delete-branch: true
          title: 'Update ${{ matrix.collection }}'
          labels:
            collections
          reviewers: EnterpriseDB/tpaexec-dev-team
          add-paths:
            collections/requirements.yml
          commit-message: |
            Update ${{ matrix.collection }} collection

            Changelog: ${{ steps.update-check.outputs.changelog }}
          body: |
            PR generated by the Ansible collection update GH workflow

            Link to changelog: ${{ steps.update-check.outputs.changelog }}
