# © Copyright EnterpriseDB UK Limited 2015-2025 - All rights reserved.

# watch for changes in .in files and call pip-compile to update the associated .txt
# runs dep check to ensure everything is fine after update.

name: Python requirements file update

# Runs on:
# pull_request
# targeting main branch
# making change to any of paths
# when PR is closed
# if PR was merged (!= closed) see jobs: section for conditional.
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - requirements*.in
      - requirements/*.in
      - tpa-ee/aap24/*.in
  workflow_dispatch:
    inputs:
      force_rebuild_pymodules:
        type: boolean
        description: 'Force rebuild of python modules'
        required: true
        default: false

env:
  CLOUDSMITH_BUILD_DEPENDENCIES_API_KEY: ${{ secrets.CLOUDSMITH_BUILD_DEPENDENCIES_API_KEY }}
  EDB_SUBSCRIPTION_TOKEN: ${{ secrets.CLOUDSMITH_READ_ALL }}
  FOUNDATION_TUNNEL_LOGIN: ${{ secrets.FOUNDATION_TUNNEL_LOGIN }}
  FORCE_REBUILD_PYMODULES: ${{ github.event.inputs.force_rebuild_pymodules }}
  GITHUB_TOKEN: ${{ secrets.GH_SLONIK }}
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  TPA_PIP_CS_API: ${{ secrets.TPA_PIP_CS_API }}

jobs:

  main:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        variant: ['-rh8', '']
    steps:
      - name: Checkout source repository
        id: checkout-source
        uses: actions/checkout@v6
        with:
          repository: EnterpriseDB/tpa-internal
          token: ${{ env.GITHUB_TOKEN }}

      - uses: ./.github/actions/install-requirements

      - name: Install python dependencies
        shell: bash
        run: |
          pip install pip-tools

      - name: Run pip-compile on requirements.in
        shell: bash
        run: |
          pip-compile -U --generate-hashes --reuse-hashes requirements${{ matrix.variant }}.in -o requirements${{ matrix.variant }}.txt

      - name: Share new requirements.txt file with next steps
        uses: actions/upload-artifact@v6
        with:
          name: new_requirements${{ matrix.variant }}
          path: requirements${{ matrix.variant }}.txt

  compile:
    needs: [main]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ppc64le, s390x]
        distro: [el]
        distro-version: [8, 9]
    outputs:
      changed: ${{ steps.dependencies.outputs.changed }}
    env:
      FILENAME_SUFFIX: ${{ matrix.distro-version == '8' && '-rh8' || '' }}
    steps:
      - name: Checkout source TPA repository
        id: checkout-source
        uses: actions/checkout@v6
        with:
          repository: EnterpriseDB/tpa-internal
          token: ${{ env.GITHUB_TOKEN }}

      - name: Checkout foundation repository branch/tag ${{ env.FOUNDATION_VER }}
        uses: actions/checkout@v6
        with:
          repository: EnterpriseDB/foundation-packaging
          ref: ${{ env.FOUNDATION_VER }}
          token: ${{ env.GITHUB_TOKEN }}
          path: foundation

      - name: Download generated requirements.txt
        uses: actions/download-artifact@v7
        with:
          name: new_requirements${{ env.FILENAME_SUFFIX }}
          path: ${{ github.workspace }}

      - name: Connect to a Native Executor
        uses: ./foundation/actions/linux/native/executor/connect
        with:
          architecture: ${{ matrix.architecture }}
          tunnel-login: ${{ env.FOUNDATION_TUNNEL_LOGIN }}

      - name: Setup container
        uses: ./foundation/actions/linux/container/setup
        with:
          architecture: ${{ matrix.architecture }}
          distro: ${{ matrix.distro }}
          distro-version: ${{ matrix.distro-version }}
          github-token: ${{ env.GITHUB_TOKEN }}
          additional-options: >
            --volume ${{ github.workspace }}:/home/runner/tpa

      - name: Execute script in container
        uses: ./foundation/actions/linux/container/execute
        env:
          FILENAME_SUFFIX: ${{ matrix.distro-version == '8' && '-rh8' || '' }}
        with:
          script: |
            cd tpa
            bash .github/workflows/requirements/check-build-dependencies.sh

      - name: tmux
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15

      - name: Nuke container
        uses: ./foundation/actions/linux/container/destroy

      - name: Share generated arch specific requirement files
        uses: actions/upload-artifact@v6
        with:
          name: requirements-${{ matrix.architecture }}${{ env.FILENAME_SUFFIX}}
          path: ${{ github.workspace }}/packages/requirements-${{ matrix.architecture }}${{ env.FILENAME_SUFFIX }}.*

  list-collections:
    name: List ansible galaxy collections
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.list-collections.outputs.changelog }}
    steps:
      - name: Checkout source repository
        id: checkout-source
        uses: actions/checkout@v6
        with:
          repository: EnterpriseDB/tpa-internal
          token: ${{ env.GITHUB_TOKEN }}

      - name: Get list of collections
        id: list-collections
        run: |
          # flag to indicate whether any changes have been made
          COLLECTION_UPDATE_FLAG="false"
          # changelog is appended to for each collection that has changes
          export CHANGELOG_PATH=$RUNNER_TEMP/changelog
          # flag file is written fresh by the script for each collection
          export FLAG_FILE=$RUNNER_TEMP/update_flag

          COLLECTIONS=$(yq -r '.collections[] | .name' collections/requirements.yml)
          for col in $COLLECTIONS; do
            chmod 755 ./.github/scripts/check_one_collection.sh
            ./.github/scripts/check_one_collection.sh $col
            if [ "$(cat $FLAG_FILE)" == "true" ]; then
              COLLECTION_UPDATE_FLAG="true"
            fi
          done

          # all changelogs that have been collected go into the output
          # if any collections at all have been changed
          if [ "$COLLECTION_UPDATE_FLAG" == "true" ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            cat $RUNNER_TEMP/changelog >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          echo "changed=$COLLECTION_UPDATE_FLAG" >> $GITHUB_OUTPUT

      - name: Upload modified requirements.yml
        if: steps.list-collections.outputs.changed == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: collection-requirements.yml
          path: ${{ github.workspace }}/collections/requirements.yml


  requirements:
    needs: [compile, list-collections]
    name: Requirements update
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_SLONIK }}

      - name: Download generated main requirements.txt
        uses: actions/download-artifact@v7
        with:
          name: new_requirements
          path: ${{ github.workspace }}

      - name: Download generated main requirements.txt for rh8
        uses: actions/download-artifact@v7
        with:
          name: new_requirements-rh8
          path: ${{ github.workspace }}
      - name: Download generated requirements.txt for ppc64le
        uses: actions/download-artifact@v7
        with:
          name: requirements-ppc64le
          path: ${{ github.workspace }}

      - name: Download generated requirements.txt for ppc64le on rh8
        uses: actions/download-artifact@v7
        with:
          name: requirements-ppc64le-rh8
          path: ${{ github.workspace }}

      - name: Download generated requirements.txt for s390x
        uses: actions/download-artifact@v7
        with:
          name: requirements-s390x
          path: ${{ github.workspace }}

      - name: Download generated requirements.txt for s390x on rh8
        uses: actions/download-artifact@v7
        with:
          name: requirements-s390x-rh8
          path: ${{ github.workspace }}

      - name: Download generated collections/requirements.yml
        uses: actions/download-artifact@v7
        with:
          name: collection-requirements.yml
          path: ${{ github.workspace }}/collections

      # we run the classic action to generate all other files and generate the PR
      - uses: ./.github/actions/update-requirements
        with:
          changelogs: ${{ needs.list-collections.outputs.changelog }}
