# © Copyright EnterpriseDB UK Limited 2015-2026 - All rights reserved.

# Single M1 Minor postgres upgrade
# with generic dimensions (os, flavor, version and failover_manager)

name: Single M1 upgrade test
run-name:
  M1 upgrade test with
  ${{ github.event.inputs.tpa_failover_manager }},
  ${{ github.event.inputs.tpa_os_image}},
  ${{ github.event.inputs.tpa_postgres_flavour }}-${{ github.event.inputs.tpa_postgres_version }}
  starting on version ${{ github.event.inputs.tpa_postgres_package_version }}
on:
  workflow_dispatch:
    inputs:
      tpa_platform:
        description: "TPA platform"
        required: false
        default: "docker"
      tpa_os_image:
        description: "TPA OS image"
        required: true
        type: choice
        options:
        - debian:11
        - debian:12
        - ubuntu:22.04
        - ubuntu:24.04
        - redhat:8
        - redhat:9
        - sles:15
      tpa_postgres_flavour:
        description: "Postgres flavour"
        required: true
        default: "postgresql"
        type: choice
        options:
        - postgresql
        - pgextended
        - edbpge
        - epas
      tpa_postgres_version:
        description: "Postgres version"
        required: true
        default: 16
        type: choice
        options:
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
      tpa_postgres_package_version:
        description: "package version to upgrade from"
        required: true
        default: "16.4*"
        type: string
      tpa_failover_manager:
        description: "Failover manager"
        required: true
        default: "repmgr"
        type: choice
        options:
        - "repmgr"
        - "efm"
        - "patroni"
      tpa_efm_bind_by_hostname:
        description: "Configure EFM to bind by hostname instead of IP (only used when tpa_failover_manager is efm)"
        required: false
        default: false
        type: boolean
      tpa_package_cache:
        description: "Use the downloader"
        type: boolean
        default: true

env:
  LANG: "C.UTF-8"
  TPA_2Q_SUBSCRIPTION_TOKEN: ${{ secrets.TPA_2Q_SUBSCRIPTION_TOKEN }}
  EDB_REPO_CREDENTIALS: ${{ secrets.EDB_REPO_CREDENTIALS }}
  EDB_REPO_CREDENTIALS_FILE: /tmp/edb_repo.conf
  EDB_SUBSCRIPTION_TOKEN: ${{ secrets.CLOUDSMITH_READ_ALL }}
  SLES_REG_TOKEN: ${{ secrets.SLES_REG_TOKEN }}

jobs:

  integration-test:
    name: >
      ${{ github.event.inputs.tpa_failover_manager }}
      ${{ github.event.inputs.tpa_os_image}}
      ${{ github.event.inputs.tpa_postgres_flavour }}-${{ github.event.inputs.tpa_postgres_version }}
      starting on version ${{ github.event.inputs.tpa_postgres_package_version }}

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source repository
        id: checkout-source
        uses: actions/checkout@v7
        with:
          repository: EnterpriseDB/tpa-internal
          token: ${{secrets.GH_SLONIK}}

      - uses: ./.github/actions/general-upgrade-test
        with:
          source_directory: ${{ github.workspace }}
          tpa_platform: ${{ github.event.inputs.tpa_platform }}
          tpa_os_image: "tpa/${{ github.event.inputs.tpa_os_image }}"
          tpa_postgres_flavour: ${{ github.event.inputs.tpa_postgres_flavour }}
          tpa_postgres_version: ${{ github.event.inputs.tpa_postgres_version }}
          tpa_postgres_package_version: ${{ github.event.inputs.tpa_postgres_package_version }}
          tpa_failover_manager: ${{ github.event.inputs.tpa_failover_manager }}
          tpa_efm_bind_by_hostname: ${{ github.event.inputs.tpa_efm_bind_by_hostname }}
          tpa_package_cache: ${{ github.event.inputs.tpa_package_cache }}
          upgrade_component_name: postgres
          upgrade_component_base_version: ${{ github.event.inputs.tpa_postgres_package_version }}
          cluster: "${{ github.event.inputs.tpa_failover_manager }}-\
            ${{ github.event.inputs.tpa_os_image }}-\
            ${{ github.event.inputs.tpa_postgres_flavour }}-\
            ${{ github.event.inputs.tpa_postgres_version }}"
